### PR TITLE
SSDP analyzer

### PR DESCRIPTION
**Pull request by jshlbrd**
This PR adds an SSDP analyzer plugin that I wrote a few months ago. I thought some might find it interesting-- thanks!

### CODE REVIEW

**Comment by 0xxon** [comment]
Hello,

thanks for this - this looks really neat. Could you perhaps add a few trace-driven testcases that check the output of the plugin against example traffic? That way we have an indication if changes break something in the plugin in the future.

**Comment by 0xxon** [comment]
Hello Josh,

I just wanted to ping again on this and check if you plan to add a few test-cases? :)

**Comment by jshlbrd** [comment]
Hi Johanna, 

Sorry for the delayed response, I'm planning to add a simple test case but don't have much free time at the moment and I always seem to run into issues getting btest to work. I'm not sure when I'll get to adding the test case ... so, you can either leave this open and I can add it when I get the chance, or close and I can resubmit once I have it up.

Thanks!

**Comment by rsmmr** [comment]
I'll go ahead and close this for now so that it doesn't keep up showing up as pending. Please reopen when ready.

**Pull request closed without merging**
