### PR TITLE
Native pf ring support

### PR DESCRIPTION
**Pull request by cardigliano**
New plugin for adding native PF_RING support to Bro.

### CODE REVIEW

**Comment by rsmmr** [comment]
Thanks, this is nice. 

I have trouble to get it to compile though, apparently because both Bro and PF_RING define their own `config.h`. Did you do anything to get around that, or did it just work for you?

Also, can I mention you as the maintainer? Assuming so, what's the right email address to contact you? (This will go into the MAINTAINER file).

Finally, I'm going to add a BSD license, ok?

**Comment by cardigliano** [comment]
@rsmmr actually it just worked for me, probably because on my system I had pf_ring headers installed, thus no config.h were found in the search paths. 
Ok for the maintainer, please use cardigliano@ntop.org.
BSD license is also fine for the plugin.

**Comment by rsmmr** [comment]
Merged with a couple small tweaks, see commit message. Please check, I don't have a good way to test it right now.

**Comment by cardigliano** [comment]
Great, I will test it ASAP.

**Pull request merged**
