### PR TITLE
Configure CMake to include CPack in order to allow the automatic

### PR DESCRIPTION
**Pull request by trixpan**
packaging of the myricom plugin

### CODE REVIEW

**Comment by trixpan** [comment]
@sethhall - I am not sure if I am alone, but for some folks using RHEL/Centos6, CPack is a very handy helper in getting Bro RPMs generated (the distro binaries are for RHEL/Centos 7) only.

So, given that bro already includes CPack, I  bolted together some code to allow folks to pack the myricom plugin as well. There's some space for improvement around RPM dependencies but I chose to refrain from being prescriptive at this stage.

e.g.:
the current settings do not require the installation of the Myricom *RPM*, so people could use the weird combination of using the plugin RPM with the myricom drivers from TGZ... 

keen to hear your thoughts

**Comment by sethhall** [comment]
Thanks for the changes, I've never even used CPack before but I'm fairly familiar with it now.  I think I need to have some discussions first before moving on this because we don't seem to have prior examples of plugins using CPack.  I would prefer to have some more generic mechanism for plugins to support CPack rather than all of the plugins having these scripts with minor differences between them.

Any thoughts you have on better ways to make this more abstract for all plugins would be appreciated as well!

**Comment by jsiwek** [comment]
Building rpm/deb packages for plugins generally should be possible now, though existing plugins would need to update their CMakeLists.txt to call into the generalized packaging configuration.  You can take a look at the new plugin skeleton for how it should end up looking:  https://github.com/bro/bro-aux/commit/a289e072b31a2605256109ff252cb2e1e587d07d

And if a plugin needs to set metdata, it can just set the appropriate variables before calling ConfigurePackaging.  E.g. you can tell from https://github.com/bro/cmake/commit/9fb8239e850bcd8c83675b4623d68b9241f135b1 what metadata can be customized.

If you try this out for the myricom plugin and find it works for your purposes, please submit an updated pull request.

**Comment by sethhall** [comment]
I broke the myricom plugin out into a package the other day and just adapted these packaging changes into it, but it still isn't quite working.  You can see it here: https://github.com/sethhall/bro-myricom

The package actually built just fine, but when I tried to install it, I got this...

```shell
[seth@control build (master)]$ sudo rpm -ivh /home/seth/bro-myricom/build/BroPluginMyricom-1.0-Linux-x86_64.rpm
error: Failed dependencies:
	libsnf.so.0()(64bit) is needed by bropluginmyricom-1.0.1-1.x86_64
	libsnf.so.0(snf_0.1)(64bit) is needed by bropluginmyricom-1.0.1-1.x86_64
```

Any thoughts about how to get this working?

**Comment by jsiwek** [comment]
Does it work to install it via `yum install *.rpm` ?

i.e. I don't think `rpm` does dependency management for you, but `yum` will.

**Comment by sethhall** [comment]
Pretty similar output.  I just realized that I don't have the myricom
package installed as an rpm package.  I need to see if I can get ahold of
that as an rpm and see if that fixes the dependency issue.

--> Processing Dependency: libsnf.so.0()(64bit) for package:
bropluginmyricom-1.0.1-1.x86_64
--> Finished Dependency Resolution
Error: Package: bropluginmyricom-1.0.1-1.x86_64
(/BroPluginMyricom-1.0-Linux-x86_64)
           Requires: libsnf.so.0()(64bit)
Error: Package: bropluginmyricom-1.0.1-1.x86_64
(/BroPluginMyricom-1.0-Linux-x86_64)
           Requires: libsnf.so.0(snf_0.1)(64bit)
 You could try using --skip-broken to work around the problem
** Found 3 pre-existing rpmdb problem(s), 'yum check' output follows:
kernel-headers-3.10.0-327.22.2.el7.x86_64 is a duplicate with
kernel-headers-3.10.0-229.20.1.el7.nfp.x86_64
kernel-tools-3.10.0-327.22.2.el7.x86_64 is a duplicate with
kernel-tools-3.10.0-229.20.1.el7.nfp.x86_64
kernel-tools-libs-3.10.0-327.22.2.el7.x86_64 is a duplicate with
kernel-tools-libs-3.10.0-229.20.1.el7.nfp.x86_64

**Comment by jsiwek** [comment]
Yeah, if yum and rpm dependency analysis only considers libraries installed as part of an rpm and not locally built/installed libs, then if there's a myricom package you can install instead, that would probably work.

But it also shouldn't matter what yum or rpm says about broken dependencies as long as you do actually have a libsnf.so.0 installed at a location that the linker will find at load-time.  i.e. you could just use the yum/rpm command line flags to skip checking for broken dependencies and force the installation of rpm.

I think you should also be able to disable automatic dependency resolution for the particular rpm that you built if you put

    set(CPACK_RPM_PACKAGE_AUTOREQPROV " no")

anytime before the `ConfigurePackaging()` call in the plugin's CMakeLists.txt.

**Comment by 0xxon** [comment]
Closing this - I think everything that was to be done here is done. Please feel free to re-open if I am wrong.

**Pull request closed without merging**
