### PR TITLE
[BIT-1543] Kafka Logger - Write Bro Logs to Kafka

### PR DESCRIPTION
**Pull request by nickwallen**
As part of the [Apache Metron](https://metron.incubator.apache.org/) project, we needed a way to send Bro logs to Kafka. From my research it seems like this is a common request.  I'd rather give this code back to the Bro community than maintain it as part of Apache Metron.

This Bro plugin logs all Bro output to Kafka.  Configuring this plugin is as simple as adding the following Bro script.

```
  @load Bro/Kafka/logs-to-kafka.bro
  redef Kafka::logs_to_send = set(Conn::LOG, HTTP::LOG, DNS::LOG);
  redef Kafka::topic_name = "bro";
  redef Kafka::kafka_conf = table(
      ["metadata.broker.list"] = "localhost:9092"
  );
```

This plugin has the following features.

- The user can specify a subset of all logs that should be sent to kafka.  For example, to only send conn, http, and dns logs, specify the following.

`redef Kafka::logs_to_send = set(Conn::LOG, HTTP::LOG, DNS::LOG);`

- Full configurability of Kafka connectivity.  Any [configuration setting accepted by the librdkafka library](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) can be passed to the plugin to tune how the logs are sent to Kafka.

```
redef Kafka::kafka_conf = table(
   ["metadata.broker.list"] = "localhost:9092",
   ["client.id"] = "bro"
);
```

- The plugin will wait a configurable period of time (for example, 3 seconds) after shutdown to attempt to send any queued messages to Kafka.

`redef Kafka::max_wait_on_shutdown = 3000;`

- There are two message formats to choose from.  By default, the standard Bro JSON format is used.  There is an alternative 'tagged JSON' format that is provided by the plugin. Currently, all messages are sent to a single Bro topic.  This 'tagged JSON' format helps a Kafka consumer distinguish which log stream the message originated from. This format prepends the log stream identifier to the JSON message.

```
{'conn': { ... }}
{'http': { ... }}
{'dns': { ... }}
```

```
redef Kafka::tag_json = T;
```

### CODE REVIEW

**Comment by nickwallen** [comment]
Created a JIRA issue for this PR.

https://bro-tracker.atlassian.net/browse/BIT-1543

**Comment by nickwallen** [comment]
@sethhall Did you have any concerns on this PR that I can address?  Thanks

**Comment by sethhall** [comment]
Sorry for the delay, could you add per-filter options similarly to how it's done in the ascii writer?
https://github.com/bro/bro/blob/master/src/logging/writers/ascii/Ascii.cc#L32

Could you also make it possible to write each log "path" into a separate queue?  If I understand the code right now, you are writing all of the logs into a single topic (which makes the tagged format make a lot more sense!).

Thanks!
  .Seth

**Comment by nickwallen** [comment]
Any reason that we want to do all of this on the same PR?

**Comment by nickwallen** [comment]
I don't mind doing those extensions, they seem very useful, but it may be easier for me to tackle one or both of those as separate PRs.  Maybe we'd get some community feedback too if we spread out the work.

**Comment by rsmmr** [comment]
Makes sense, I'll work on merging it in, and then we can go from there. I have one request: do you mind changing the license to BSD? That's what we generally use for the plugin repository.

**Comment by nickwallen** [comment]
Sure, not a problem.  Will change license to BSD.

**Comment by nickwallen** [comment]
License changed to BSD.  Also, squashed commits.  Thanks

**Comment by rsmmr** [comment]
Thanks!

Which version of librdkafka are you using? I just installed the latest librdkafka from GitHub and am getting this when I compile the plugin:

```
/usr/local/include/librdkafka/rdkafkacpp.h:1098:11: error: invalid use of destructor ‘~RdKafka::Queue’ as a type virtual ~Queue () { }
```

(Not immediately sure what's wrong with that code there from a quick look.)

**Comment by nickwallen** [comment]
Ouch.  I'll take a look and get back to you.

**Comment by nickwallen** [comment]
I am using version 0.8.6 which is marked as the [latest release version](https://github.com/edenhill/librdkafka/releases/tag/0.8.6), I believe.  I have installed it using [Homebrew](http://brew.sh/) on my Mac.  I also manually installed using these commands and it builds successfully for me.

```
wget https://github.com/edenhill/librdkafka/archive/0.8.6.tar.gz
tar xvzf 0.8.6.tar.gz
cd librdkafka-0.8.6/
./configure
make
sudo make install
```

Would you mind trying with v0.8.6?

**Comment by nickwallen** [comment]
I do see the same behavior as you when installing the latest librdkafka from master.

```
git clone https://github.com/edenhill/librdkafka.git
brew link --force openssl
./configure
make
sudo make install
```

```
nallen@foo: ~/Development/bro-plugins/kafka
$ make
make: [build-it] Error 1 (ignored)
( cd build && make )
Scanning dependencies of target generate_outputs
[  0%] Built target generate_outputs
Scanning dependencies of target bif-plugin-BRO_KAFKA-kafka.bif
[  9%] [BIFCL] Processing src/kafka.bif
[  9%] Built target bif-plugin-BRO_KAFKA-kafka.bif
Scanning dependencies of target bro-plugin-BRO_KAFKA
[ 18%] Creating build/lib/bif for BRO::KAFKA
[ 18%] Built target bro-plugin-BRO_KAFKA
Scanning dependencies of target copy-scripts-BRO_KAFKA
[ 18%] Built target copy-scripts-BRO_KAFKA
Scanning dependencies of target copy-bif-BRO_KAFKA
[ 27%] Creating build/lib/bif for BRO::KAFKA
[ 27%] Built target copy-bif-BRO_KAFKA
Scanning dependencies of target bif-init-BRO_KAFKA
[ 27%] Built target bif-init-BRO_KAFKA
Scanning dependencies of target BRO-KAFKA.darwin-x86_64
[ 36%] Building CXX object CMakeFiles/BRO-KAFKA.darwin-x86_64.dir/src/KafkaWriter.cc.o
In file included from /Users/nallen/Development/bro-plugins/kafka/src/KafkaWriter.cc:7:
In file included from /Users/nallen/Development/bro-plugins/kafka/src/KafkaWriter.h:5:
/usr/local/include/librdkafka/rdkafkacpp.h:1098:11: error: function definition does not declare parameters
  virtual ~Queue () { }
          ^
1 error generated.
make[3]: *** [CMakeFiles/BRO-KAFKA.darwin-x86_64.dir/src/KafkaWriter.cc.o] Error 1
make[2]: *** [CMakeFiles/BRO-KAFKA.darwin-x86_64.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [build-it] Error 2
```

**Comment by rsmmr** [comment]
I'll use 0.8.6, no problem, just wanted to make sure it's a local issue over here somehow.

**Comment by nickwallen** [comment]
This was merged, correct?  Should this PR be closed?

**Comment by rsmmr** [comment]
Yes, it's merged. Not sure why github didn't pick up on it.

**Pull request closed without merging**
