### PR TITLE
Adding initial conversion of TCPRS to a plugin

### PR DESCRIPTION
**Pull request by jswaro**
TCPRS is TCP traffic analyzer that specializes in the detection
and classification of retransmission and network reordering events.

The following forms of events are available in the TCPRS analyzer:

* Dead connection detection
* TCP option detection
* Retransmission detection and classification
* Limited Transmit and Fast Recovery detection
* Network reordering detection and classification
* RTT and initial RTO measurements

Included with the analyzer is a collection of 103 test cases that
are used for iterative design and refinement of the analyzer. Each
test case is used to verify a specific function of the analyzer or
general classification of events.

Signed-off-by: James Swaro <james.swaro@gmail.com>

### CODE REVIEW

**Comment by jswaro** [comment]
Copying the comments from the previous PR



I've commited some changes to topic/robin/tcprs-merge, see commit
message. With that, it now works with current master.

A couple more requests:

    Please add a README that gives a bit more context about the plugin, including what it can measure and examples how to use it.

    In scripts/*, please document all exported elements using Broxygen comments (see other scripts how that looks like).

    Indentation/formatting seems inconsistent across the scripts.

And two suggestions (optional):

    Using a global variable, TCPRS::enabled, to turn on the analyzer isn't the nicest way of doing that, as it requires redefs in the other scripts when loaded. I think a better way would be a bif function TCPRS::enable() that would then be called from bro_init() handlers.

    Why not move all the TCPRS scripts into a single TCPRS namespace, rather than having several independent ones across the scripts?

**Comment by jswaro** [comment]
@rsmmr 
 
So, I've seemingly fixed the requests from above, but I'm unfamiliar with the first suggestion. How would that work?

Secondly, the TCPRS scripts could be moved into a single namespace, I have no problems with that, but I'm not entirely sure what you mean by that.

**Comment by jswaro** [comment]
I'll rebase this to a single commit after it's approved.

**Comment by rsmmr** [comment]
Re TCPRS::enable(): that would just be a bif function coming with your analyzer that, for example, would set a static member variable inside your analyzer class. Broker, e.g., has an enable() function, it's  defined in `src/broker/comm.bif` (that one calls a method of the Broker manager though, which you don't have; hence the thought of a static member).

Re namespaces: I meant that instead of having TCPRTT, TCPRECOVERY, TCPOSFP, etc; you'd just have everything in TCPRS. Does that make sense?

(When you're ready, please rebase on top of topic/robin/tcprs-merge.)

**Comment by rsmmr** [comment]
What's the state here?

**Comment by jswaro** [comment]
I've been working heavily on my thesis defense prep work. I'm intending to
close this soon by addressing your suggestions. I was hoping to work on it
today actually.

James Swaro

**Comment by jswaro** [comment]
Robin, I've been trying to add the namespace changes and some of it doesn't make sense.

Each of those files has a different log file as they have a different Info format. Putting them into the same namespace would seem to be the wrong thing to do as they differ from each other log/object type.

I agree that putting the events into a TCPRS namespace makes sense though.

**Comment by jswaro** [comment]
@rsmmr 
Robin, I've pulled in the remaining changes to the best of my knowledge. I don't think I can rebase on your tcprs-merge branch, as it might be a bit dated. 

This branch is currently rebased to bro-plugins/master, so it should be merge-able in the current state. If you have any questions about the code changes, I'd be more than happy to explain them.

**Comment by jswaro** [comment]
I wanted to touch base on this. Is it possible to have this merged soon?

**Comment by rsmmr** [comment]
Is the branch actually working for you in the current state? It doesn't compile for me with master, and when I fix that compiler error, the test-suite fails. Unless I'm missing something here ...

Also, because you didn't rebase on top of my branch, I had to reapply a number of my changes. Your branch wasn't even using the __preload__ feature yet that we came up with to support putting rtx_stats into a namespace.

Your branch also isn't adding any Broxygen comments. You've added a few to event handlers, but there they won't work. What you instead should be doing is document the exported stuff, in particular the Info records. The events' documentation you should then put into the *.bif file (see existing event bifs).

I've pushed a new branch with my changes, but the test suite still fails in the same way. I've pushed my new branch to topic/robin/tcprs-merge-again. If you want to keep iterating, start from that one now. Or maybe you should just maintain this plugin outside of Bro, it's been taking a while now already.

**Comment by jswaro** [comment]
> Is the branch actually working for you in the current state? It doesn't
compile for me with master, and when I fix that compiler error, the
test-suite fails.

What failed?

> Also, because you didn't rebase on top of my branch, I had to reapply a
number of my changes. Your branch wasn't even using the *preload* feature
yet that we came up with to support putting rtx_stats into a namespace.

Sorry about that. I must have missed it in the diff comparison.

> Your branch also isn't adding any Broxygen comments. You've added a few
to event handlers, but there they won't work. What you instead should be
doing is document the exported stuff, in particular the Info records. The
events' documentation you should then put into the *.bif file (see existing
event bifs).

I'll fix the Broxygen comments.

I'll start from there. Hopefully, I should be able to fix this tonight.

James Swaro

**Comment by jswaro** [comment]
I've been going over your rebased branch but I can't tell what has changed. The PR was working with master but needs to be rebased with master in order to become mergable again. Where did the scripts go? 

The error that I am seeing is the following: 
> fatal error in [path]/init-bare.bro, line 1: Component 'Analyzer::TCPRS' defined more than once.

**Comment by jswaro** [comment]
Nevermind my last post. I had an older version of the plugin still present in the install folder. 

Where did the scripts go? Without knowing what was changed in the scripts, I'll have difficulty debugging the issue that you are seeing.

**Comment by rsmmr** [comment]
Sorry, forgot to commit the scripts are moving them around. Pushed now.

**Comment by jswaro** [comment]
Thanks!

**Comment by jswaro** [comment]
@rsmmr 
This looks like another problem I saw a while ago while doing the initial conversion with the name spaces. If the event isn't in the exact namespace, the event isn't defined and never fires. There aren't any warnings, so no logs are created and that looks like what is happening here. 

I'm in meetings all day, but I'm going to keep looking at it. Do you have any ideas?

**Comment by jswaro** [comment]
Robin, when the scripts moved and changed namespaces from jswaro::TCPRS, the show-plugin test was not changed to reflect the namespace changed.

**Comment by jswaro** [comment]
The other problem is the refactoring of the 'HookAddToAnalyzerTree', which is now 'HookSetupAnalyzerTree'. This is why the events were not being fired off.

**Comment by jswaro** [comment]
I finished running the unit tests and all of them pass.

**Comment by rsmmr** [comment]
great, that's working for me as well now, will merge.

**Comment by jswaro** [comment]
Careful during the merge. I noticed that there is a merge conflict in the README and Makefile in the Bro-Plugin base directory. This is likely due to the fact this PR hasn't been rebased to the bro/master branch.

**Pull request merged**
